default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.77.3
    hooks:
      - id: terraform_validate
        stages: [commit]
      - id: terraform_fmt
        args:
          - --args=-no-color
          - --args=-diff
          - --args=-write=false
      - id: terraform_tflint
        args:
          - --args=--module
